### ISSUE TITLE
Problem bei Zugriff auf account.html

### ISSUE THREAD

**Issue by Chris3362** [thm-projects/arsnova-docker#1]
Die Docker Instanz lässt sich starten und ich bekomme auch den entsprechenden View generiert. Wenn ich allerdings auf den ARSNova Button klicke, werde ich an http://arsnova.example.org/customization/account.html?redirect=%2Fmobile%2F weitergeleitet und bekomme einen 404 Fehler. Wo liegt mein Fehler?

**Comment by aitech4** [comment]
Hello, 
i have the same problem  as Chris3362. Can somebody help out with that issue? Best regards

**Comment by dgerhardt** [comment]
Static customization files are now part of the image.

**Comment by Rillke** [comment]
Shouldn't static files be part of the nginx image?
