### ISSUE TITLE
Email Registration Problem

### ISSUE THREAD

**Issue by Chris3362** [thm-projects/arsnova-docker#4]
Currently I am trying to register a user. The system then tries to send an email with an activation link. Unfortunately I can't configure an SMTP server, is there a way to log in directly after registration?

**Comment by dgerhardt** [comment]
Have you tried setting `ARSNOVA_MAIL_HOST` in `webapp.env`?

**Comment by Chris3362** [comment]
I have set the parameter `ARSNOVA_MAIL_HOST`. I have looked at the arsnova.properties.example, but unfortunately I can't find any settings for SMTP, Mail Account, Mail Password. Is there a way to disable activation after registration?

**Comment by dgerhardt** [comment]
There is currently no support for SMTP authentication. But it's something, we have planned to support in the future. Till then you need a local mail server. Account activation cannot be disabled.
