### ISSUE TITLE
Missing signal forwarding in arsnova-webapp/docker-entrypoint.sh

### ISSUE THREAD

**Issue by Rillke** [thm-projects/arsnova-docker#6]
When `sh` and friends are used as entry points the way they are, they have PID 1. Having PID 1, they do not forward `SIGTERM` to their child processes. Consequently tomcat does not get `SIGTERM` and gets `SIGKILL`ed after 10s of waiting after a `docker stop`.

[This article](https://hynek.me/articles/docker-signals/) features some work-arounds. [Read this one](https://medium.com/@gchudnov/trapping-signals-in-docker-containers-7a57fdda7d86), if you'd like to play with signals in your shell code.

**Comment by Rillke** [comment]
The same applies to the nginx image.

**Comment by dgerhardt** [comment]
Thank you for reporting this. There is no reason to run the server processes as subprocess so I will add the missing `exec`s.
