### ISSUE TITLE
Building images: docker-compose build fails with error

### ISSUE THREAD

**Issue by ArtiShelar** [thm-projects/arsnova-docker#8]
Trying to build images for ARSnova as per the given instructions.
The 'docker-compose build' command fails while building the 'webapp' service. 
Error received is as follows:

Package tomcat8 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'tomcat8' has no installation candidate
ERROR: Service 'webapp' failed to build: The command '/bin/sh -c apt-get update &&   apt-get install -y --no-install-recommends     gawk     libservlet3.1-java     libtcnative-1     python     tomcat8   &&   apt-get clean &&   rm -rf /
var/lib/apt/lists/*' returned a non-zero code: 100

Requesting your help to understand what is going wrong here.

**Comment by Rillke** [comment]
This means that `openjdk:8-jre` is now based on a new operation system which does not ship `tomcat8`. You probably have to use a newer Tomcat version. According to [this](https://github.com/thm-projects/arsnova-docker/blob/2.7/arsnova-webapp/Dockerfile) and [this](https://packages.debian.org/search?suite=buster&arch=any&searchon=names&keywords=tomcat), you most likely need tomcat9

**Comment by ArtiShelar** [comment]
Thank you for the quick response.

I tried to update the dockerfile to replace `tomcat8` with `tomcat9`, but that is also giving me an error.

---> Running in d87023b6ee49
**/bin/sh: 1: cannot create /etc/tomcat9/conf/Catalina/localhost/customization.xml: Directory nonexistent**
ERROR: Service 'webapp' failed to build: The command '/bin/sh -c curl -fsSLO "$ARSNOVA_CONFIG_URL" &&   mkdir /etc/arsnova &&   sed     -e ':a;N;$!ba;s/\\\n *//g'     arsnova.properties.example |     sed     -e 's/^\(socketio.bind-addr
ess *= *\).*/\10.0.0.0/g'     -e '/^#socketio.proxy-path *=/s/^#//g'     -e 's/^#\(session.guest-session.cleanup-days *= *\).*/\10/g'     -e 's/^#\(user.cleanup-days *= *\).*/\10/g' |     gawk '{       match($0, /^(# ?)?([a-z0-9._-]+)(
 *= *)(.*)$/, a);       if (RLENGTH != -1) {         b = gensub(/[.-]/, "_", "g", a[2]);         defaultVal = "";         if (!a[1]) defaultVal = a[4];         out = a[2] a[3] "${ARSNOVA_" toupper(b) ":" defaultVal "}";       } else {
        out = $0;       }       print out;     }'     > /etc/arsnova/arsnova.properties &&   rm arsnova.properties.example &&   sed -i "s#</Host>#  $TOMCAT_VALVE\n\n      </Host>#g" /etc/tomcat9/server.xml &&   printf '<?xml version="1
.0" encoding="UTF-8"?>\n<Context docBase="/opt/arsnova/customization" path="/customization"/>\n' > /etc/tomcat9/conf/Catalina/localhost/customization.xml' returned a non-zero code: 2

When updating the dockerfile to have `tomcat9`, is there some other configuration that will also need to be updated ?

**Comment by ArtiShelar** [comment]
@Rillke, is there anything you could help me with, in order to solve the above problem ?

**Comment by tekay** [comment]
@ArtiShelar thanks for opening the issue, there is indeed a problem with tomcat8 being out of date.
I'm looking into that.

We offer pre-built docker images which should still be usable - is there a reason you want to build the docker images yourself?

**Comment by Rillke** [comment]
> is there anything you could help me with, in order to solve the above problem ?

I'd say get a support contract with the company behind this software. Otherwise you could just compare `$CATALINA_HOME` and `$CATALINA_BASE` between tomcat 8 and tomcat 9 in Debian,  [read the docs](https://tomcat.apache.org/tomcat-9.0-doc/) [especially the `Virtual Hosting` part] or use `find / -type d localhost` inside a previous build step of the container to look up where the `localhost` directory ended up, if it exists at all.

**Comment by tekay** [comment]
Opened a PR for installing tomcat8 from backports (https://github.com/thm-projects/arsnova-docker/pull/9)

If you want, you can check that branch out and test it.

**Comment by ArtiShelar** [comment]
> @ArtiShelar thanks for opening the issue, there is indeed a problem with tomcat8 being out of date.
> I'm looking into that.
> 
> We offer pre-built docker images which should still be usable - is there a reason you want to build the docker images yourself?

Hi @tekay, I'm working on making some small changes in the application, because of which I will need to build my own packages and deploy them in docker. That is the reason why I was building my own images.

**Comment by ArtiShelar** [comment]
> > is there anything you could help me with, in order to solve the above problem ?
> 
> I'd say get a support contract with the company behind this software. Otherwise you could just compare `$CATALINA_HOME` and `$CATALINA_BASE` between tomcat 8 and tomcat 9 in Debian, [read the docs](https://tomcat.apache.org/tomcat-9.0-doc/) [especially the `Virtual Hosting` part] or use `find / -type d localhost` inside a previous build step of the container to look up where the `localhost` directory ended up, if it exists at all.

Yes, I already tried installing tomcat9 separately to see whether the directory structure has changed, so that I could put the correct path in the dockerfile. However, I do see the path `/etc/tomcat9/Catalina/localhost` on my server.

![image](https://user-images.githubusercontent.com/25084990/83407300-ba490100-a410-11ea-9470-aa42884456e2.png)

**Comment by tekay** [comment]
> Hi @tekay, I'm working on making some small changes in the application, because of which I will need to build my own packages and deploy them in docker. That is the reason why I was building my own images.

I see, makes sense. 

Problem with tomcat9 is that we didn't test it and probably never will. I'd suggest either testing the PR yourself or waiting on us to test / merge this.

**Comment by ArtiShelar** [comment]
Thank you for your insights, @tekay and @Rillke 
We will keep trying on our end, at least until your tests are completed.

**Comment by tekay** [comment]
@ArtiShelar There is a fix in the `master` branch now. We upgraded to tomcat9.
